title: "RubyGeeks"
url: "http://www.rubygeeks.com"

author: "Senthil Nayagam"
email: "senthil@rubygeeks.com"
description: "meeting point for rubygeeks"

auto: false
source: .
destination: ./public
paginate: 10
permalink: /:year/:month/:title

markdown: rdiscount
pygments: false

exclude:
  - README.markdown
  - _drafts
